services:
  php:
    image: ${IMAGES_PREFIX:-}symfony-vite-php
    restart: unless-stopped
    volumes:
      - php_socket:/var/run/php

  caddy:
    image: ${IMAGES_PREFIX:-}symfony-vite-caddy
    # depends_on:
    # php:
    # condition: service_healthy
    # restart: true
    environment:
      SERVER_NAME: ${SERVER_NAME:-localhost}, caddy:80
    restart: unless-stopped
    volumes:
      - php_socket:/var/run/php
      - caddy_data:/data
      - caddy_config:/config
    ports:
      - target: 80
        published: ${HTTP_PORT:-80}
        protocol: tcp

      - target: 443
        published: ${HTTPS_PORT:-443}
        protocol: tcp

      # HTTP/3
      - target: 443
        published: ${HTTP3_PORT:-443}
        protocol: udp

volumes:
  php_socket:
  caddy_data:
    external: true
  caddy_config:
